In [1]:
import torch
import numpy as np

In [2]:
torch.tensor(9)

tensor(9)

In [3]:
torch.tensor([2,5])

tensor([2, 5])

In [9]:
scalar = torch.tensor(10)

In [10]:
scalar

tensor(10)

In [11]:
scalar + 5

tensor(15)

In [12]:
scalar.dim()

0

In [13]:
scalar.shape

torch.Size([])

In [31]:
vector = torch.tensor([2,3,3])

In [32]:
vector.shape

torch.Size([3])

In [33]:
vector.dim()

1

In [34]:
vector.dtype

torch.int64

In [37]:
matrix = torch.tensor([[2,3,3], [2,5,3]])

In [38]:
matrix.dim()

2

In [39]:
matrix.shape

torch.Size([2, 3])

In [40]:
tensor = torch.tensor([[[2,3,1],[1,2,3]]])

In [41]:
tensor.shape

torch.Size([1, 2, 3])

In [42]:
tensor.dim()

3

In [57]:
random_matrix = torch.rand(size=(3,3))

In [58]:
random_matrix

tensor([[0.5771, 0.8670, 0.0919],
        [0.0527, 0.2501, 0.3791],
        [0.4927, 0.1079, 0.4724]])

In [59]:
torch.matmul(random_matrix,random_matrix)

tensor([[0.4240, 0.7271, 0.4251],
        [0.2304, 0.1492, 0.2787],
        [0.5228, 0.5052, 0.3093]])

In [60]:
x = torch.arange(1,10,2)

In [61]:
x

tensor([1, 3, 5, 7, 9])

In [62]:
x_reshaped = x.reshape(1,5)

In [63]:
x_reshaped

tensor([[1, 3, 5, 7, 9]])

In [68]:
x_reshaped.size()

torch.Size([1, 5])

In [69]:
x_reshaped.shape

torch.Size([1, 5])

In [70]:
x_reshaped.is_contiguous()

True

In [71]:
x_reshaped.T.is_contiguous()

True

In [73]:
y = x_reshaped.T
y.is_contiguous()

True

In [74]:
a = torch.rand(size=(224,224,3))
a.shape

torch.Size([224, 224, 3])

In [76]:
a_permuted = a.permute(2,0,1)
a_permuted.shape

torch.Size([3, 224, 224])

In [77]:
torch.cuda.is_available()

True